# Generated by Django 2.2.9 on 2020-05-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200421_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_final',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha_inicial',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='consultas',
            field=models.ManyToManyField(blank=True, related_name='opiniones', to='core.Consulta'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='opiniones',
            field=models.ManyToManyField(related_name='tags', to='core.Opinion'),
        ),
    ]
