# Generated by Django 2.2.9 on 2020-05-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200505_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuenteAPI',
        ),
    ]
