# Generated by Django 2.2.9 on 2020-05-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_fuenteapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='peticion',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='url',
            field=models.URLField(db_index=True),
        ),
    ]
